// Generated by CoffeeScript 1.3.3
var http, q, request, server, server_port, url;

http = require("http");

q = require("querystring");

url = require("url");

server_port = process.env.PORT || 9006;

server = http.createServer().listen(server_port);

request = require('request');

server.on("request", function(req, res) {
  var callbackFn, params;
  params = url.parse(req.url, true).query;
  if (params.callback !== void 0 && params.callback !== "") {
    callbackFn = params.callback;
  } else {
    callbackFn = "callback";
  }
  if (params.url === void 0 || params.url === "") {
    res.write("" + callbackFn + " (" + (JSON.stringify({
      status: "ERROR",
      message: "missing url parameter"
    })) + ");");
    res.end();
    return;
  }
  return request.post({
    uri: params.url,
    json: params
  }, function(error, response, body) {
    if (response.statusCode === 201) {
      res.write("" + callbackFn + " (" + (JSON.stringify(body)) + ");");
    } else if (response.statusCode === 400) {
      res.write("" + callbackFn + " ({ 'error':'" + (JSON.stringify(body)) + "', 'code': '" + response.statusCode + "' });");
    } else {
      res.write("" + callbackFn + " ({ 'error':'" + body + "', 'code': '" + response.statusCode + "' });");
    }
    return res.end();
  });
});

console.log("post proxy running on " + server_port);
